### ISSUE TITLE
Download link needed

### ISSUE THREAD

**Issue by Insidi0usAngel** [Dawjaw/HoeUtilitiesV3#4]
I saw the hoeutilitiesv3 download link posted on a discord server but before I got round to using it the discord server has been deleted but here it says there is no release...  If there is a working beta version of this mod I would like to try it please :)

**Comment by sideloads** [comment]
Dude... This repo is the module itself
Download the repo as a zip file and unzip it into a new folder, name it HoeUtilitiesV3 or something, then drag it into your modules folder.
